server:
  port: 80
  servlet:
    context-path: /myipl  #http://localhost:8080/myipl/swagger-ui.html 
    
    
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myipl?autoReconnect=true&rewriteBatchedStatements=true&createDatabaseIfNotExist=true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
security: 
  basic:
    enabled: false